language: node_js
os:
  - linux
node_js:
  - "iojs"
  - "node"
script:
  - "npm test"
  - "npm run coverage"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
  code_climate:
    repo_token: 14e6dec822455f51da491b00b538b49afe6d439ff395f471ed122b1dcfe2e359
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g gulp
after_script:
  - ./node_modules/.bin/lcov-result-merger './coverage/*.info'| codeclimate