web:
  build: .
  command: npm start
  ports:
    - "4000:4000"
  links:
    - db
  volumes:
    - .:/usr/src/app
  environment:
    - MONGOLAB_URI
db:
  image: mongo:3.0
  ports:
    - "27017:27018"
  volumes:
    - db:/data/db